//! KGP unicode-placeholder icon system.
//!
//! At startup we transmit a sprite PNG for every known icon kind to the kitty
//! terminal with `a=t,U=1,i=<id>,f=100`. After that, drawing an icon is a
//! single-cell glyph: the unicode placeholder char `U+10EEEE`, with the image
//! ID encoded into the foreground color (kitty interprets the FG color of a
//! placeholder cell as a 24-bit image id).
//!
//! Single-cell placements don't need row/col diacritics — kitty defaults to
//! cell (0, 0) of the image, which for our 32×32 sprites is the whole sprite.
//!
//! Generated by `tools/gen_icons.py` → `assets/icons/*.png`.

use anyhow::Result;
use base64::Engine;
use ratatui::style::Color;
use std::io::Write;

/// Unicode placeholder cell — the placeholder codepoint plus row(0)/col(0)
/// diacritics so kitty unambiguously maps it to cell (0,0) of the image.
/// Combining marks have zero width, so the whole string occupies one cell.
pub const PLACEHOLDER: &str = "\u{10EEEE}\u{0305}\u{0305}";

/// One row's worth of sprite metadata. IDs start at 1.
struct Sprite {
    name: &'static str,
    bytes: &'static [u8],
}

macro_rules! sprite {
    ($name:expr) => {
        Sprite {
            name: $name,
            bytes: include_bytes!(concat!("../assets/icons/", $name, ".png")),
        }
    };
}

/// Static table — index + 1 == image ID transmitted to kitty.
static SPRITES: &[Sprite] = &[
    // languages / data
    sprite!("rs"), sprite!("c"), sprite!("cpp"), sprite!("py"),
    sprite!("js"), sprite!("ts"), sprite!("html"), sprite!("css"),
    sprite!("lua"), sprite!("go"), sprite!("zig"), sprite!("java"),
    sprite!("rb"), sprite!("php"), sprite!("sh"), sprite!("md"),
    sprite!("toml"), sprite!("json"), sprite!("yaml"), sprite!("xml"),
    sprite!("txt"), sprite!("log"), sprite!("conf"),
    // archives / binaries / fonts / docs
    sprite!("archive"), sprite!("exe"), sprite!("iso"), sprite!("font"),
    sprite!("pdf"), sprite!("lock"),
    // folders
    sprite!("folder"), sprite!("folder_open"), sprite!("folder_dl"),
    sprite!("folder_docs"), sprite!("folder_pics"), sprite!("folder_vid"),
    sprite!("folder_music"), sprite!("folder_cfg"), sprite!("folder_git"),
    sprite!("folder_proj"), sprite!("folder_node"), sprite!("folder_trash"),
    sprite!("folder_cache"), sprite!("folder_home"),
    // specials
    sprite!("readme"), sprite!("license"), sprite!("makefile"),
    sprite!("dockerfile"), sprite!("cargo"), sprite!("gitignore"),
    sprite!("package"), sprite!("env"),
    // misc
    sprite!("symlink"), sprite!("file_generic"),
    sprite!("image"), sprite!("video"), sprite!("audio"),
];

/// Resolve an icon-kind keyword to an image ID (1..=N). 0 means "no sprite".
pub fn id_for(name: &str) -> u32 {
    for (i, s) in SPRITES.iter().enumerate() {
        if s.name == name {
            return (i + 1) as u32;
        }
    }
    0
}

/// FG color encoding for a given image ID.
/// Kitty reads the 24-bit FG color as the image ID directly.
pub fn id_color(id: u32) -> Color {
    let r = ((id >> 16) & 0xff) as u8;
    let g = ((id >> 8) & 0xff) as u8;
    let b = (id & 0xff) as u8;
    Color::Rgb(r, g, b)
}

/// Send every sprite to kitty as a virtual image (used by unicode placeholders).
/// Safe to call once at app startup; subsequent calls are idempotent on the
/// kitty side because we re-use the same image IDs.
pub fn transmit_all<W: Write>(out: &mut W) -> Result<()> {
    for (i, sprite) in SPRITES.iter().enumerate() {
        let id = (i + 1) as u32;
        transmit_one(out, id, sprite.bytes)?;
    }
    out.flush()?;
    Ok(())
}

fn transmit_one<W: Write>(out: &mut W, id: u32, png: &[u8]) -> Result<()> {
    let b64 = base64::engine::general_purpose::STANDARD.encode(png);
    let bytes = b64.as_bytes();
    let chunk_size = 4096;
    let chunks: Vec<&[u8]> = bytes.chunks(chunk_size).collect();
    let count = chunks.len();

    for (i, chunk) in chunks.iter().enumerate() {
        let m = if i == count - 1 { 0 } else { 1 };
        if i == 0 {
            // First chunk: full APC. q=2 silences responses.
            write!(
                out,
                "\x1b_Ga=t,U=1,i={id},f=100,t=d,q=2,m={m};{}\x1b\\",
                std::str::from_utf8(chunk)?
            )?;
        } else {
            write!(
                out,
                "\x1b_Gm={m},q=2;{}\x1b\\",
                std::str::from_utf8(chunk)?
            )?;
        }
    }
    Ok(())
}
